version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    container_name: rr-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rr-network

  redis:
    image: redis:7-alpine
    container_name: rr-redis
    ports:
      - "6379:6379"
    networks:
      - rr-network

  # JAEGER: 1 container duy nhất cho Tracing (Thay thế SigNoz)
  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: rr-jaeger
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - rr-network

  krakend:
    image: devopsfaith/krakend:2
    container_name: rr-krakend
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8081:8081"
    networks:
      - rr-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - jaeger

networks:
  rr-network:
    name: rr-network
    driver: bridge

volumes:
  postgres_data:
