-- Logistics Service Seed Data
-- This file seeds the points of interest (Farmers, Roasteries, Retailers) for the Vietnam region.

-- 1. Locations (Static Points of Interest)
INSERT INTO locations (id, name, type, lat, lng) VALUES
-- Farmers
('FARM_CAU_DAT', 'Nông trại Cầu Đất (Arabica)', 'FARM', 11.895, 108.538),
('FARM_BMT', 'Nông trại Buôn Ma Thuột (Robusta)', 'FARM', 12.666, 108.038),
('FARM_PLEIKU', 'Nông trại Pleiku (Blend)', 'FARM', 14.010, 108.040),

-- Roasteries
('WH_SONG_THAN', 'Xưởng rang KCN Sóng Thần (Bình Dương)', 'ROASTERY', 10.880, 106.750),
('WH_HOA_LAC', 'Xưởng rang KCN Hòa Lạc (Hà Nội)', 'ROASTERY', 21.010, 105.530),
('WH_HOA_KHANH', 'Xưởng rang KCN Hòa Khánh (Đà Nẵng)', 'ROASTERY', 16.080, 108.150),

-- Retailers
('RET_HCM', 'Cửa hàng Quận 1, TP.HCM', 'RETAILER', 10.776, 106.700),
('RET_HN', 'Cửa hàng Hoàn Kiếm, Hà Nội', 'RETAILER', 21.028, 105.852),
('RET_DN', 'Cửa hàng Hải Châu, Đà Nẵng', 'RETAILER', 16.066, 108.216)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    type = EXCLUDED.type,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng;

-- 2. Vehicles (Initial Fleet)
INSERT INTO vehicles (id, plate_number, type, capacity_kg) VALUES
('VEH_TRUCK_001', '51C-12345', 'TRUCK', 5000),
('VEH_TRUCK_002', '29H-67890', 'TRUCK', 5000),
('VEH_VAN_001', '43A-11111', 'VAN', 1000)
ON CONFLICT (id) DO NOTHING;

-- 3. Drivers (Seed drivers linked to identities)
-- Note: UUIDs should ideally match the ones generated by Identity Service
INSERT INTO drivers (id, name, phone, vehicle_id, is_available) VALUES
('00000000-0000-0000-0000-000000000001', 'Driver Alpha', '0901234567', 'VEH_TRUCK_001', true),
('00000000-0000-0000-0000-000000000002', 'Driver Beta', '0907654321', 'VEH_TRUCK_002', true)
ON CONFLICT (id) DO NOTHING;
