package usecase

import (
	"context"
	"fmt"

	"RuntimeRoasters/apps/farm-service/internal/domain"
	"RuntimeRoasters/pkg/base/identity"
	"RuntimeRoasters/pkg/errs"
)

type FarmUsecase interface {
	CreateFarm(ctx context.Context, farm *domain.Farm) (*domain.Farm, error)
	GetFarm(ctx context.Context, id uint64) (*domain.Farm, error)
	ListFarms(ctx context.Context) ([]*domain.Farm, error)
	UpdateFarm(ctx context.Context, farm *domain.Farm) (*domain.Farm, error)
	DeleteFarm(ctx context.Context, id uint64) error
}

type farmUsecase struct {
	repo FarmRepository
}

func NewFarmUsecase(repo FarmRepository) FarmUsecase {
	return &farmUsecase{
		repo: repo,
	}
}

func (u *farmUsecase) CreateFarm(ctx context.Context, farm *domain.Farm) (*domain.Farm, error) {
	user, ok := identity.FromContext(ctx)
	if !ok {
		return nil, errs.ErrUnauthorized
	}

	if (user.Role == domain.RoleAdmin || user.Role == domain.RoleFarmAdmin) && farm.OwnerID != "" {
		// Admin can specify owner
	} else {
		farm.OwnerID = user.Subject
	}

	// ID will be auto-generated by the database (BIGSERIAL)
	if err := farm.Validate(); err != nil {
		return nil, fmt.Errorf("%w: %v", errs.ErrValidation, err)
	}

	if err := u.repo.Create(ctx, farm); err != nil {
		return nil, err
	}

	return farm, nil
}

func (u *farmUsecase) GetFarm(ctx context.Context, id uint64) (*domain.Farm, error) {
	return u.repo.GetByID(ctx, id)
}

func (u *farmUsecase) ListFarms(ctx context.Context) ([]*domain.Farm, error) {
	return u.repo.List(ctx)
}

func (u *farmUsecase) UpdateFarm(ctx context.Context, farm *domain.Farm) (*domain.Farm, error) {
	user, ok := identity.FromContext(ctx)
	if !ok {
		return nil, errs.ErrUnauthorized
	}

	current, err := u.repo.GetByID(ctx, farm.ID)
	if err != nil {
		return nil, err
	}

	if farm.Name == "" {
		farm.Name = current.Name
	}
	if farm.Location == "" {
		farm.Location = current.Location
	}
	if farm.Area == 0 {
		farm.Area = current.Area
	}
	if farm.CoffeeType == "" {
		farm.CoffeeType = current.CoffeeType
	}

	if (user.Role == domain.RoleAdmin || user.Role == domain.RoleFarmAdmin) && farm.OwnerID != "" {
		// Admin can specify owner
	} else {
		farm.OwnerID = current.OwnerID
	}

	if err := farm.Validate(); err != nil {
		return nil, fmt.Errorf("%w: %v", errs.ErrValidation, err)
	}

	if err := u.repo.Update(ctx, farm); err != nil {
		return nil, err
	}

	return farm, nil
}

func (u *farmUsecase) DeleteFarm(ctx context.Context, id uint64) error {
	// Authorization is now handled at Gate 1 (Interceptor) and Gate 2 (Repository Scope)
	return u.repo.Delete(ctx, id)
}
