// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dungxbuif/RuntimeRoasters/apps/demo-service/config"
	"github.com/dungxbuif/RuntimeRoasters/apps/demo-service/internal/delivery/grpc"
	"github.com/dungxbuif/RuntimeRoasters/apps/demo-service/internal/usecase"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base"
	"github.com/dungxbuif/RuntimeRoasters/pkg/database"
	"github.com/dungxbuif/RuntimeRoasters/pkg/redis"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig := config.Load()
	options := provideBaseOptions(configConfig)
	app := base.NewApp(options)
	config2 := provideConfigPtr(configConfig)
	postgresConfig := providePostgresConfig(configConfig)
	db, err := database.NewPostgres(postgresConfig)
	if err != nil {
		return nil, nil, err
	}
	redisConfig := provideRedisConfig(configConfig)
	client := redis.NewClient(redisConfig)
	demoUsecase := usecase.NewDemoUsecase()
	demoHandler := grpc.NewDemoHandler(demoUsecase)
	appApp := NewApp(app, config2, db, client, demoHandler)
	return appApp, func() {
	}, nil
}

// wire.go:

func provideConfigPtr(cfg config.Config) *config.Config {
	return &cfg
}

func provideBaseOptions(cfg config.Config) base.Options {
	return base.Options{
		Name:   "demo-service",
		Config: cfg.BaseConfig,
	}
}

func providePostgresConfig(cfg config.Config) database.PostgresConfig {
	return database.PostgresConfig{
		URL: cfg.DatabaseURL,
	}
}

func provideRedisConfig(cfg config.Config) redis.Config {
	return redis.Config{
		Addr: cfg.RedisAddr,
	}
}
