// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dungxbuif/RuntimeRoasters/apps/demo-service/config"
	"github.com/dungxbuif/RuntimeRoasters/apps/demo-service/internal/delivery/grpc"
	"github.com/dungxbuif/RuntimeRoasters/apps/demo-service/internal/usecase"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base/auth/provider"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base/auth/transport/grpc"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base/casbin"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base/casbin/transport/grpc"
	"github.com/dungxbuif/RuntimeRoasters/pkg/database"
	"github.com/dungxbuif/RuntimeRoasters/pkg/redis"
	grpc2 "google.golang.org/grpc"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig := config.Load()
	keyProvider, err := provideKeyProvider(configConfig)
	if err != nil {
		return nil, nil, err
	}
	authSnapshotClient, err := provideCasbinClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	engine, err := provideCasbinEngine(authSnapshotClient)
	if err != nil {
		return nil, nil, err
	}
	v := provideGRPCServerOptions(keyProvider, engine, configConfig)
	options := provideBaseOptions(configConfig, v)
	app := base.NewApp(options)
	config2 := provideConfigPtr(configConfig)
	postgresConfig := providePostgresConfig(configConfig)
	db, err := database.NewPostgres(postgresConfig)
	if err != nil {
		return nil, nil, err
	}
	redisConfig := provideRedisConfig(configConfig)
	client := redis.NewClient(redisConfig)
	demoUsecase := usecase.NewDemoUsecase()
	demoHandler := grpc.NewDemoHandler(demoUsecase)
	appApp := NewApp(app, config2, db, client, keyProvider, engine, demoHandler)
	return appApp, func() {
	}, nil
}

// wire.go:

func provideConfigPtr(cfg config.Config) *config.Config {
	return &cfg
}

func provideKeyProvider(cfg config.Config) (provider.KeyProvider, error) {
	ttl, _ := time.ParseDuration(cfg.JWKSCacheTTL)
	return provider.NewJWKSCache(cfg.JWKSURL, cfg.InternalSecret, ttl)
}

func provideCasbinClient(cfg config.Config) (casbin.AuthSnapshotClient, error) {
	return casbingrpc.NewAuthSnapshotClient(cfg.AuthServiceAddr, "demo-service")
}

func provideCasbinEngine(client casbin.AuthSnapshotClient) (casbin.Engine, error) {

	modelText := `
[request_definition]
r = sub, obj, act
[policy_definition]
p = sub, obj, act
[role_definition]
g = _, _
[policy_effect]
e = some(where (p.eft == allow))
[matchers]
m = g(r.sub, "admin") || (g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act))
`
	return casbin.NewResilientReader(client, casbin.ReaderOptions{
		ModelText:     modelText,
		SyncInterval:  10 * time.Minute,
		RetryInterval: 5 * time.Second,
	})
}

func provideGRPCServerOptions(keyProvider provider.KeyProvider, casbinEngine casbin.Engine, cfg config.Config) []grpc2.ServerOption {
	return []grpc2.ServerOption{grpc2.ChainUnaryInterceptor(authgrpc.GRPCUnaryInterceptor(keyProvider, cfg.ExpectedIssuer), casbingrpc.GRPCUnaryInterceptor(casbinEngine)),
	}
}

func provideBaseOptions(cfg config.Config, grpcOpts []grpc2.ServerOption) base.Options {
	return base.Options{
		Name:              "demo-service",
		Config:            cfg.BaseConfig,
		GRPCServerOptions: grpcOpts,
	}
}

func providePostgresConfig(cfg config.Config) database.PostgresConfig {
	return database.PostgresConfig{
		URL: cfg.DatabaseURL,
	}
}

func provideRedisConfig(cfg config.Config) redis.Config {
	return redis.Config{
		Addr: cfg.RedisAddr,
	}
}
