// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: runtime/farm/v1/farm.proto

package farmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FarmService_CreateFarm_FullMethodName       = "/runtime.farm.v1.FarmService/CreateFarm"
	FarmService_GetFarm_FullMethodName          = "/runtime.farm.v1.FarmService/GetFarm"
	FarmService_ListFarms_FullMethodName        = "/runtime.farm.v1.FarmService/ListFarms"
	FarmService_UpdateFarm_FullMethodName       = "/runtime.farm.v1.FarmService/UpdateFarm"
	FarmService_DeleteFarm_FullMethodName       = "/runtime.farm.v1.FarmService/DeleteFarm"
	FarmService_CreateHarvest_FullMethodName    = "/runtime.farm.v1.FarmService/CreateHarvest"
	FarmService_GetHarvest_FullMethodName       = "/runtime.farm.v1.FarmService/GetHarvest"
	FarmService_ListFarmHarvests_FullMethodName = "/runtime.farm.v1.FarmService/ListFarmHarvests"
)

// FarmServiceClient is the client API for FarmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FarmService defines the management of coffee farms.
type FarmServiceClient interface {
	// CreateFarm creates a new farm record.
	CreateFarm(ctx context.Context, in *CreateFarmRequest, opts ...grpc.CallOption) (*CreateFarmResponse, error)
	// GetFarm retrieves a single farm by ID.
	GetFarm(ctx context.Context, in *GetFarmRequest, opts ...grpc.CallOption) (*GetFarmResponse, error)
	// ListFarms returns all farms owned by the authenticated user.
	ListFarms(ctx context.Context, in *ListFarmsRequest, opts ...grpc.CallOption) (*ListFarmsResponse, error)
	// UpdateFarm updates an existing farm's details.
	UpdateFarm(ctx context.Context, in *UpdateFarmRequest, opts ...grpc.CallOption) (*UpdateFarmResponse, error)
	// DeleteFarm removes a farm record.
	DeleteFarm(ctx context.Context, in *DeleteFarmRequest, opts ...grpc.CallOption) (*DeleteFarmResponse, error)
	// CreateHarvest records a new harvesting batch.
	CreateHarvest(ctx context.Context, in *CreateHarvestRequest, opts ...grpc.CallOption) (*CreateHarvestResponse, error)
	// GetHarvest retrieves details of a specific harvest batch.
	GetHarvest(ctx context.Context, in *GetHarvestRequest, opts ...grpc.CallOption) (*GetHarvestResponse, error)
	// ListFarmHarvests returns all harvest batches for a specific farm.
	ListFarmHarvests(ctx context.Context, in *ListFarmHarvestsRequest, opts ...grpc.CallOption) (*ListFarmHarvestsResponse, error)
}

type farmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFarmServiceClient(cc grpc.ClientConnInterface) FarmServiceClient {
	return &farmServiceClient{cc}
}

func (c *farmServiceClient) CreateFarm(ctx context.Context, in *CreateFarmRequest, opts ...grpc.CallOption) (*CreateFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_CreateFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) GetFarm(ctx context.Context, in *GetFarmRequest, opts ...grpc.CallOption) (*GetFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_GetFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) ListFarms(ctx context.Context, in *ListFarmsRequest, opts ...grpc.CallOption) (*ListFarmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFarmsResponse)
	err := c.cc.Invoke(ctx, FarmService_ListFarms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) UpdateFarm(ctx context.Context, in *UpdateFarmRequest, opts ...grpc.CallOption) (*UpdateFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_UpdateFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) DeleteFarm(ctx context.Context, in *DeleteFarmRequest, opts ...grpc.CallOption) (*DeleteFarmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFarmResponse)
	err := c.cc.Invoke(ctx, FarmService_DeleteFarm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) CreateHarvest(ctx context.Context, in *CreateHarvestRequest, opts ...grpc.CallOption) (*CreateHarvestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHarvestResponse)
	err := c.cc.Invoke(ctx, FarmService_CreateHarvest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) GetHarvest(ctx context.Context, in *GetHarvestRequest, opts ...grpc.CallOption) (*GetHarvestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHarvestResponse)
	err := c.cc.Invoke(ctx, FarmService_GetHarvest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *farmServiceClient) ListFarmHarvests(ctx context.Context, in *ListFarmHarvestsRequest, opts ...grpc.CallOption) (*ListFarmHarvestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFarmHarvestsResponse)
	err := c.cc.Invoke(ctx, FarmService_ListFarmHarvests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FarmServiceServer is the server API for FarmService service.
// All implementations must embed UnimplementedFarmServiceServer
// for forward compatibility.
//
// FarmService defines the management of coffee farms.
type FarmServiceServer interface {
	// CreateFarm creates a new farm record.
	CreateFarm(context.Context, *CreateFarmRequest) (*CreateFarmResponse, error)
	// GetFarm retrieves a single farm by ID.
	GetFarm(context.Context, *GetFarmRequest) (*GetFarmResponse, error)
	// ListFarms returns all farms owned by the authenticated user.
	ListFarms(context.Context, *ListFarmsRequest) (*ListFarmsResponse, error)
	// UpdateFarm updates an existing farm's details.
	UpdateFarm(context.Context, *UpdateFarmRequest) (*UpdateFarmResponse, error)
	// DeleteFarm removes a farm record.
	DeleteFarm(context.Context, *DeleteFarmRequest) (*DeleteFarmResponse, error)
	// CreateHarvest records a new harvesting batch.
	CreateHarvest(context.Context, *CreateHarvestRequest) (*CreateHarvestResponse, error)
	// GetHarvest retrieves details of a specific harvest batch.
	GetHarvest(context.Context, *GetHarvestRequest) (*GetHarvestResponse, error)
	// ListFarmHarvests returns all harvest batches for a specific farm.
	ListFarmHarvests(context.Context, *ListFarmHarvestsRequest) (*ListFarmHarvestsResponse, error)
	mustEmbedUnimplementedFarmServiceServer()
}

// UnimplementedFarmServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFarmServiceServer struct{}

func (UnimplementedFarmServiceServer) CreateFarm(context.Context, *CreateFarmRequest) (*CreateFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFarm not implemented")
}
func (UnimplementedFarmServiceServer) GetFarm(context.Context, *GetFarmRequest) (*GetFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFarm not implemented")
}
func (UnimplementedFarmServiceServer) ListFarms(context.Context, *ListFarmsRequest) (*ListFarmsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFarms not implemented")
}
func (UnimplementedFarmServiceServer) UpdateFarm(context.Context, *UpdateFarmRequest) (*UpdateFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFarm not implemented")
}
func (UnimplementedFarmServiceServer) DeleteFarm(context.Context, *DeleteFarmRequest) (*DeleteFarmResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFarm not implemented")
}
func (UnimplementedFarmServiceServer) CreateHarvest(context.Context, *CreateHarvestRequest) (*CreateHarvestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHarvest not implemented")
}
func (UnimplementedFarmServiceServer) GetHarvest(context.Context, *GetHarvestRequest) (*GetHarvestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHarvest not implemented")
}
func (UnimplementedFarmServiceServer) ListFarmHarvests(context.Context, *ListFarmHarvestsRequest) (*ListFarmHarvestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFarmHarvests not implemented")
}
func (UnimplementedFarmServiceServer) mustEmbedUnimplementedFarmServiceServer() {}
func (UnimplementedFarmServiceServer) testEmbeddedByValue()                     {}

// UnsafeFarmServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FarmServiceServer will
// result in compilation errors.
type UnsafeFarmServiceServer interface {
	mustEmbedUnimplementedFarmServiceServer()
}

func RegisterFarmServiceServer(s grpc.ServiceRegistrar, srv FarmServiceServer) {
	// If the following call pancis, it indicates UnimplementedFarmServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FarmService_ServiceDesc, srv)
}

func _FarmService_CreateFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).CreateFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_CreateFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).CreateFarm(ctx, req.(*CreateFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_GetFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).GetFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_GetFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).GetFarm(ctx, req.(*GetFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_ListFarms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFarmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).ListFarms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_ListFarms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).ListFarms(ctx, req.(*ListFarmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_UpdateFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).UpdateFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_UpdateFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).UpdateFarm(ctx, req.(*UpdateFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_DeleteFarm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFarmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).DeleteFarm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_DeleteFarm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).DeleteFarm(ctx, req.(*DeleteFarmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_CreateHarvest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHarvestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).CreateHarvest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_CreateHarvest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).CreateHarvest(ctx, req.(*CreateHarvestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_GetHarvest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHarvestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).GetHarvest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_GetHarvest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).GetHarvest(ctx, req.(*GetHarvestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FarmService_ListFarmHarvests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFarmHarvestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarmServiceServer).ListFarmHarvests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FarmService_ListFarmHarvests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarmServiceServer).ListFarmHarvests(ctx, req.(*ListFarmHarvestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FarmService_ServiceDesc is the grpc.ServiceDesc for FarmService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FarmService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.farm.v1.FarmService",
	HandlerType: (*FarmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFarm",
			Handler:    _FarmService_CreateFarm_Handler,
		},
		{
			MethodName: "GetFarm",
			Handler:    _FarmService_GetFarm_Handler,
		},
		{
			MethodName: "ListFarms",
			Handler:    _FarmService_ListFarms_Handler,
		},
		{
			MethodName: "UpdateFarm",
			Handler:    _FarmService_UpdateFarm_Handler,
		},
		{
			MethodName: "DeleteFarm",
			Handler:    _FarmService_DeleteFarm_Handler,
		},
		{
			MethodName: "CreateHarvest",
			Handler:    _FarmService_CreateHarvest_Handler,
		},
		{
			MethodName: "GetHarvest",
			Handler:    _FarmService_GetHarvest_Handler,
		},
		{
			MethodName: "ListFarmHarvests",
			Handler:    _FarmService_ListFarmHarvests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/farm/v1/farm.proto",
}
