// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dungxbuif/RuntimeRoasters/apps/auth-service/config"
	"github.com/dungxbuif/RuntimeRoasters/apps/auth-service/internal/delivery/grpc"
	"github.com/dungxbuif/RuntimeRoasters/apps/auth-service/internal/infrastructure/casbin"
	"github.com/dungxbuif/RuntimeRoasters/pkg/base"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig := config.Load()
	options := provideBaseOptions(configConfig)
	app := base.NewApp(options)
	config2 := provideConfigPtr(configConfig)
	enforcer, err := provideCasbinEnforcer(configConfig)
	if err != nil {
		return nil, nil, err
	}
	handler := grpc.NewHandler(enforcer)
	appApp := NewApp(app, config2, enforcer, handler)
	return appApp, func() {
	}, nil
}

// wire.go:

func provideConfigPtr(cfg config.Config) *config.Config {
	return &cfg
}

func provideCasbinEnforcer(cfg config.Config) (*casbin.Enforcer, error) {
	return casbin.NewEnforcer(cfg.DatabaseURL)
}

func provideBaseOptions(cfg config.Config) base.Options {
	return base.Options{
		Name:   "auth-service",
		Config: cfg.BaseConfig,
	}
}
